//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.09 at 02:22:33 PM IST 
//


package com.pvmsys.brix.graph.xml.mapping.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="element" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="elementItem" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="itvsAttribute" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="graphAttribute" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="graphElement" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "element"
})
@XmlRootElement(name = "elements")
public class Elements {

    protected List<Elements.Element> element;

    /**
     * Gets the value of the element property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the element property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Elements.Element }
     * 
     * 
     */
    public List<Elements.Element> getElement() {
        if (element == null) {
            element = new ArrayList<Elements.Element>();
        }
        return this.element;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="elementItem" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="itvsAttribute" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="graphAttribute" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="graphElement" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "elementItem"
    })
    public static class Element {

        protected List<Elements.Element.ElementItem> elementItem;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "iscompulsory")
        protected boolean iscompulsory;
        @XmlAttribute(name = "primaryAttribute")
        protected String primaryAttribute;
        @XmlAttribute(name = "isOptional")
        protected boolean isOptional;

        
        public boolean getIscompulsory()
		{
			return iscompulsory;
		}

		public void setIscompulsory(boolean iscompulsory)
		{
			this.iscompulsory = iscompulsory;
		}
		
		public boolean getIsOptional()
		{
			return isOptional;
		}

		public void setIsOptional(boolean isOptional)
		{
			this.isOptional = isOptional;
		}
		
		public String getPrimaryAttribute()
		{
			return primaryAttribute;
		}

		public void setPrimaryAttribute(String primaryAttribute)
		{
			this.primaryAttribute = primaryAttribute;
		}

		/**
         * Gets the value of the elementItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the elementItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElementItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Elements.Element.ElementItem }
         * 
         * 
         */
        public List<Elements.Element.ElementItem> getElementItem() {
            if (elementItem == null) {
                elementItem = new ArrayList<Elements.Element.ElementItem>();
            }
            return this.elementItem;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="itvsAttribute" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="graphAttribute" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "graphAttribute","dataType"
        })
        public static class ElementItem {

            @XmlAttribute(name = "graphAttribute")
            protected String graphAttribute;
            
            @XmlAttribute(name = "dataType")
            protected String dataType;
           
            /**
             * Gets the value of the graphAttribute datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getdataType() {
				return dataType;
			}
            /**
             * Sets the value of the graphAttribute datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
			public void setdataType(String dataType) {
				this.dataType = dataType;
			}

			/**
             * Gets the value of the graphAttribute property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGraphAttribute() {
                return graphAttribute;
            }

            /**
             * Sets the value of the graphAttribute property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGraphAttribute(String value) {
                this.graphAttribute = value;
            }

        }

    }

}
