//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.27 at 02:43:01 PM IST 
//


package com.pvmsys.brix.graph.configreader.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for columnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="columnType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="columnnumber" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="columnid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ismergedcolumn" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="mergewithcolumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "columnType", propOrder = {
    "value"
})
public class Column {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "columnnumber")
    protected int columnnumber;
    @XmlAttribute(name = "columnid")
    protected String columnid;
    @XmlAttribute(name = "ismergedcolumn")
    protected boolean ismergedcolumn;
    @XmlAttribute(name = "mergewithcolumn")
    protected String mergewithcolumn;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the columnnumber property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public int getColumnnumber() {
        return columnnumber;
    }

    /**
     * Sets the value of the columnnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setColumnnumber(int value) {
        this.columnnumber = value;
    }


	/**
     * Gets the value of the columnid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnid() {
        return columnid;
    }

    /**
     * Sets the value of the columnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnid(String value) {
        this.columnid = value;
    }

    /**
     * Gets the value of the ismergedcolumn property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public boolean getIsmergedcolumn() {
        return ismergedcolumn;
    }

    /**
     * Sets the value of the ismergedcolumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setIsmergedcolumn(boolean value) {
        this.ismergedcolumn = value;
    }

    /**
     * Gets the value of the mergewithcolumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMergewithcolumn() {
        return mergewithcolumn;
    }

    /**
     * Sets the value of the mergewithcolumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMergewithcolumn(String value) {
        this.mergewithcolumn = value;
    }
    
    
    /* (non-Javadoc)
   	 * @see java.lang.Object#toString()
   	 */
   	@Override
   	public String toString() {
   		return "Column [value=" + value + ", columnnumber=" + columnnumber + ", columnid=" + columnid
   				+ ", ismergedcolumn=" + ismergedcolumn + ", mergewithcolumn=" + mergewithcolumn + "]";
   	}

}
