//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.27 at 02:43:01 PM IST 
//


package com.pvmsys.brix.graph.configreader.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for layoutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="layoutType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="row" type="{}rowType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="layoutid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="noofrows" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="noofcolumns" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="columnwidth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "layoutType", propOrder = {
    "row"
})
public class Layout {

    protected List<Row> row;
	@XmlAttribute(name = "layoutid")
    protected String layoutid;
    @XmlAttribute(name = "noofrows")
    protected int noofrows;
    @XmlAttribute(name = "noofcolumns")
    protected int noofcolumns;
    @XmlAttribute(name = "columnwidth")
    protected String[] columnwidth;

    /**
     * Gets the value of the row property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the row property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Row }
     * 
     * 
     */
    public List<Row> getRow() {
        if (row == null) {
            row = new ArrayList<Row>();
        }
        return this.row;
    }
    
    
    /**
   	 * @param row the row to set
   	 */
   	public void setRow(List<Row> row) {
   		this.row = row;
   	}

   	/**
   	 * @param noofcolumns the noofcolumns to set
   	 */
   	public void setNoofcolumns(int noofcolumns) {
   		this.noofcolumns = noofcolumns;
   	}

    /**
     * Gets the value of the layoutid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayoutid() {
        return layoutid;
    }

    /**
     * Sets the value of the layoutid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayoutid(String value) {
        this.layoutid = value;
    }

    /**
     * Gets the value of the noofrows property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public int getNoofrows() {
        return noofrows;
    }

    /**
     * Sets the value of the noofrows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setNoofrows(int value) {
        this.noofrows = value;
    }

    /**
     * Gets the value of the noofcolumns property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public int getNoofcolumns() {
        return noofcolumns;
    }

    /**
     * Sets the value of the noofcolumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setNoofcolumns(Byte value) {
        this.noofcolumns = value;
    }

    /**
     * Gets the value of the columnwidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String[] getColumnwidth() {
        return columnwidth;
    }

    /**
     * Sets the value of the columnwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnwidth(String[] value) {
        this.columnwidth = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Layout [row=" + row + ", layoutid=" + layoutid + ", noofrows=" + noofrows + ", noofcolumns="
				+ noofcolumns + ", columnwidth=" + columnwidth + "]";
	}
    
    
    

}
