//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 09:45:02 AM IST 
//


package com.pvmsys.brix.graph.configreader.beans;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for nodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nodeType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="nodetype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parametername" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="businessobject" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orderby" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="child" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nodeType", propOrder = {
    "value"
})
public class Node {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "nodetype")
    protected String nodetype;
    @XmlAttribute(name = "parametername")
    protected String parametername;
    @XmlAttribute(name = "businessobject")
    protected String businessobject;
    @XmlAttribute(name = "orderby")
    protected String orderby;
    @XmlAttribute(name = "child")
    protected String child;
    @XmlAttribute(name = "parent")
    protected String parent;
    /*@XmlTransient
    protected int level;*/
    
    @XmlTransient
    protected String id;
    
    @XmlTransient
    protected boolean open;
    
    public boolean getOpen() {
		return open;
	}

	public void setOpen(boolean open) {
		this.open = open;
	}

	public String getLink() {
		return link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	/*public List<Node> getData() {
		return data;
	}

	public void setData(List<Node> data) {
		this.data = data;
	}
*/
	@XmlTransient
    protected String link;
    
    //childNodes
    @XmlTransient
    List<Node> data;
    
    /**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the level
	 */
	/*public int getLevel() {
		return level;
	}

	*//**
	 * @param level the level to set
	 *//*
	public void setLevel(int level) {
		this.level = level;
	}*/

	/**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the nodetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodetype() {
        return nodetype;
    }

    /**
     * Sets the value of the nodetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodetype(String value) {
        this.nodetype = value;
    }

    /**
     * Gets the value of the parametername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametername() {
        return parametername;
    }

    /**
     * Sets the value of the parametername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametername(String value) {
        this.parametername = value;
    }

    /**
     * Gets the value of the businessobject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessobject() {
        return businessobject;
    }

    /**
     * Sets the value of the businessobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessobject(String value) {
        this.businessobject = value;
    }

    /**
     * Gets the value of the orderby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderby() {
        return orderby;
    }

    /**
     * Sets the value of the orderby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderby(String value) {
        this.orderby = value;
    }

    /**
     * Gets the value of the child property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChild() {
        return child;
    }

    /**
     * Sets the value of the child property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChild(String value) {
        this.child = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }
    /**
     * Gets the list of the childs.
     * 
     * @return
     *     possible object is
     *     {@link List<Node> }
     *     
     */
	public List<Node> getChildNodes() {
		return data;
	}
	 /**
     * Sets the list of the child nodes.
     * 
     * @param value
     *     allowed object is
     *     {@link List<Node> }
     *     
     */
	public void setChildNodes(List<Node> childNodes) {
		this.data = childNodes;
	}

	@Override
	public String toString() {
		return "Node [value=" + value + ", nodetype=" + nodetype + ", parametername=" + parametername
				+ ", businessobject=" + businessobject + ", orderby=" + orderby + ", child=" + child + ", parent="
				+ parent  + ", id=" + id + ", childNodes=" + data + "]";
	}
    
    

}
