//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 09:45:02 AM IST 
//


package com.pvmsys.brix.graph.configreader.beans;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for parameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parameterType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="businessobject" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="displaytype" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="layoutid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="columncount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="defaultvalue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isvisible" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="searchtype" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="values" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orderby" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relationname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="columnid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="defaultvaluefrom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="defaultvalueto" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subfilter" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="filtertype" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameterType", propOrder = {
    "value"
})
public class Parameter {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "key")
    protected String key;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "businessobject")
    protected String businessobject;
    @XmlAttribute(name = "displaytype")
    protected String displaytype;
    @XmlAttribute(name = "layoutid")
    protected String layoutid;
    @XmlAttribute(name = "columncount")
    protected String columncount;
    @XmlAttribute(name = "defaultvalue")
    protected String defaultvalue;
    @XmlAttribute(name = "isvisible")
    protected String isvisible;
    @XmlAttribute(name = "searchtype")
    protected String searchtype;
    @XmlAttribute(name = "source")
    protected String source;
    @XmlAttribute(name = "values")
    protected String values;
    @XmlAttribute(name = "orderby")
    protected String orderby;
    @XmlAttribute(name = "relationname")
    protected String relationname;
    @XmlAttribute(name = "defaultvaluefrom")
    protected String defaultvaluefrom;
    @XmlAttribute(name = "defaultvalueto")
    protected String defaultvalueto;
    @XmlAttribute(name = "subfilter")
    protected String subfilter;
    @XmlAttribute(name = "filtertype")
    protected String filtertype;
    
    @XmlTransient
    protected String id;
    
    
    @XmlTransient
    protected String[] filterValues;
    
    public String[] getFilterValues() {
		return filterValues;
	}

	public void setFilterValues(String[] filterValues) {
		this.filterValues = filterValues;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@XmlTransient
    private String dataType;
    
    @XmlTransient
    private int length;
    
    @XmlTransient
    private Date fromDate;
    
    @XmlTransient
    private Date toDate;
    
    @XmlTransient
    private Date date;
    
    /**
	 * @return the fromDate
	 */
	public Date getFromDate() {
		return fromDate;
	}

	/**
	 * @param fromDate the fromDate to set
	 */
	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	/**
	 * @return the toDate
	 */
	public Date getToDate() {
		return toDate;
	}

	/**
	 * @param toDate the toDate to set
	 */
	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}
	
	/**
	 * @return the fdate
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * @param date the date to set
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * @return the dataType
	 */
	public String getDataType() {
		return dataType;
	}

	/**
	 * @param dataType the dataType to set
	 */
	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	/**
	 * @return the length
	 */
	public int getLength() {
		return length;
	}

	/**
	 * @param length the length to set
	 */
	public void setLength(int length) {
		this.length = length;
	}

	/**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the businessobject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessobject() {
        return businessobject;
    }

    /**
     * Sets the value of the businessobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessobject(String value) {
        this.businessobject = value;
    }

    /**
     * Gets the value of the displaytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplaytype() {
        return displaytype;
    }

    /**
     * Sets the value of the displaytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplaytype(String value) {
        this.displaytype = value;
    }

    /**
     * Gets the value of the layoutid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayoutid() {
        return layoutid;
    }

    /**
     * Sets the value of the layoutid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayoutid(String value) {
        this.layoutid = value;
    }

    /**
     * Gets the value of the columncount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumncount() {
        return columncount;
    }

    /**
     * Sets the value of the columncount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumncount(String value) {
        this.columncount = value;
    }

    /**
     * Gets the value of the defaultvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultvalue() {
        return defaultvalue;
    }

    /**
     * Sets the value of the defaultvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultvalue(String value) {
        this.defaultvalue = value;
    }

    /**
     * Gets the value of the isvisible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsvisible() {
        return isvisible;
    }

    /**
     * Sets the value of the isvisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsvisible(String value) {
        this.isvisible = value;
    }

    /**
     * Gets the value of the searchtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchtype() {
        return searchtype;
    }

    /**
     * Sets the value of the searchtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchtype(String value) {
        this.searchtype = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValues(String value) {
        this.values = value;
    }

    /**
     * Gets the value of the orderby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderby() {
        return orderby;
    }

    /**
     * Sets the value of the orderby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderby(String value) {
        this.orderby = value;
    }

    /**
     * Gets the value of the relationname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationname() {
        return relationname;
    }

    /**
     * Sets the value of the relationname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationname(String value) {
        this.relationname = value;
    }


    /**
     * Gets the value of the defaultvaluefrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultvaluefrom() {
        return defaultvaluefrom;
    }

    /**
     * Sets the value of the defaultvaluefrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultvaluefrom(String value) {
        this.defaultvaluefrom = value;
    }

    /**
     * Gets the value of the defaultvalueto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultvalueto() {
        return defaultvalueto;
    }

    /**
     * Sets the value of the defaultvalueto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultvalueto(String value) {
        this.defaultvalueto = value;
    }

    /**
     * Gets the value of the subfilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubfilter() {
        return subfilter;
    }

    /**
     * Sets the value of the subfilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubfilter(String value) {
        this.subfilter = value;
    }

    /**
     * Gets the value of the filtertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiltertype() {
        return filtertype;
    }

    /**
     * Sets the value of the filtertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiltertype(String value) {
        this.filtertype = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Parameter [value=" + value + ", key=" + key + ", name=" + name + ", businessobject=" + businessobject
				+ ", displaytype=" + displaytype + ", layoutid=" + layoutid + ", columncount=" + columncount
				+ ", defaultvalue=" + defaultvalue + ", isvisible=" + isvisible + ", searchtype=" + searchtype
				+ ", source=" + source + ", values=" + values + ", orderby=" + orderby + ", relationname="
				+ relationname + ", defaultvaluefrom=" + defaultvaluefrom + ", defaultvalueto=" + defaultvalueto
				+ ", subfilter=" + subfilter + ", filtertype=" + filtertype + ", dataType=" + dataType + ", length="
				+ length + ", fromDate=" + fromDate + ", toDate=" + toDate + ", date=" + date + "]";
	}
    
    

}
