
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 09:45:02 AM IST 
//

package com.pvmsys.brix.graph.configreader.beans;



import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for searchconfigurationsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="searchconfigurationsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="search" type="{}searchType"/>
 *         &lt;element name="ENUMS" type="{}ENUMSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchconfigurationsType", propOrder = {
    "search",
    "enums"
})
public class SearchConfigurations {

    @XmlElement(required = true)
    protected List<SearchBean> search;
    @XmlElement(name = "ENUMS", required = true)
    protected ENUMSType enums;

    /**
     * Gets the value of the search property.
     * 
     * @return
     *     possible object is
     *     {@link SearchBean }
     *     
     */
    public List<SearchBean> getSearch() {
        return search;
    }

    /**
     * Sets the value of the search property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchBean }
     *     
     */
    public void setSearch(List<SearchBean> value) {
    	if(value==null){
    		value = new ArrayList<>();
    	}
        this.search = value;
    }

    /**
     * Gets the value of the enums property.
     * 
     * @return
     *     possible object is
     *     {@link ENUMSType }
     *     
     */
    public ENUMSType getENUMS() {
        return enums;
    }

    /**
     * Sets the value of the enums property.
     * 
     * @param value
     *     allowed object is
     *     {@link ENUMSType }
     *     
     */
    public void setENUMS(ENUMSType value) {
        this.enums = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "SearchConfigurations [search=" + search + ", enums=" + enums + "]";
	} 
    

}
