

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 09:45:02 AM IST 
//

package com.pvmsys.brix.graph.configreader.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="searchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="criteria" type="{}criteriaType"/>
 *         &lt;element name="results" type="{}resultsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="userpreference" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="projectbasedsecurity" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="outputobject" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchType", propOrder = {
    "criteria",
    "results"
})
public class SearchBean {

    @XmlElement(required = true)
    protected Criteria criteria;
    @XmlElement(required = true)
    protected Results results;
    @XmlAttribute(name = "key")
    protected String key;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "userpreference")
    protected Byte userpreference;
    @XmlAttribute(name = "projectbasedsecurity")
    protected Byte projectbasedsecurity;
    @XmlAttribute(name = "outputobject")
    protected String outputobject;
    
    @XmlTransient
    protected String searchName;
    
    @XmlTransient
    protected String searchType;
    
    
    @XmlTransient
    protected String responsetype;

    public String getResponsetype() {
		return responsetype;
	}

	public void setResponsetype(String responsetype) {
		this.responsetype = responsetype;
	}

	/**
	 * @return the searchName
	 */
	public String getSearchName() {
		return searchName;
	}

	/**
	 * @param searchName the searchName to set
	 */
	public void setSearchName(String searchName) {
		this.searchName = searchName;
	}

	/**
	 * @return the searchType
	 */
	public String getSearchType() {
		return searchType;
	}

	/**
	 * @param searchType the searchType to set
	 */
	public void setSearchType(String searchType) {
		this.searchType = searchType;
	}

	/**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link Criteria }
     *     
     */
    public Criteria getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Criteria }
     *     
     */
    public void setCriteria(Criteria value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link Results }
     *     
     */
    public Results getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link Results }
     *     
     */
    public void setResults(Results value) {
        this.results = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the userpreference property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getUserpreference() {
        return userpreference;
    }

    /**
     * Sets the value of the userpreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setUserpreference(Byte value) {
        this.userpreference = value;
    }

    /**
     * Gets the value of the projectbasedsecurity property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getProjectbasedsecurity() {
        return projectbasedsecurity;
    }

    /**
     * Sets the value of the projectbasedsecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setProjectbasedsecurity(Byte value) {
        this.projectbasedsecurity = value;
    }

    /**
     * Gets the value of the outputobject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputobject() {
        return outputobject;
    }

    /**
     * Sets the value of the outputobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputobject(String value) {
        this.outputobject = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "SearchBean [criteria=" + criteria + ", results=" + results + ", key=" + key + ", description="
				+ description + ", userpreference=" + userpreference + ", projectbasedsecurity=" + projectbasedsecurity
				+ ", outputobject=" + outputobject + "]";
	}
    
    

}
