//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.12 at 03:50:50 PM IST 
//


package com.pvmsys.brix.graph.mappings.webServices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HodsWebService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HodsWebService">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="URL" type="{}URL"/>
 *         &lt;element name="Password" type="{}Password"/>
 *         &lt;element name="Username" type="{}Username"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="functionalGroupId" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="isImportRequired" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HodsWebService", propOrder = {
    "url",
    "password",
    "username"
})
public class HodsWebService {

    @XmlElement(name = "URL", required = true)
    protected URL url;
    @XmlElement(name = "Password", required = true)
    protected Password password;
    @XmlElement(name = "Username", required = true)
    protected Username username;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "functionalGroupId")
    protected String functionalGroupId;
    @XmlAttribute(name = "isImportRequired")
    protected boolean isImportRequired;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link URL }
     *     
     */
    public URL getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link URL }
     *     
     */
    public void setURL(URL value) {
        this.url = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link Password }
     *     
     */
    public Password getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link Password }
     *     
     */
    public void setPassword(Password value) {
        this.password = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link Username }
     *     
     */
    public Username getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link Username }
     *     
     */
    public void setUsername(Username value) {
        this.username = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the functionalGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public String getFunctionalGroupId() {
        return functionalGroupId;
    }

    /**
     * Sets the value of the functionalGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFunctionalGroupId(String value) {
        this.functionalGroupId = value;
    }

    /**
     * Gets the value of the isImportRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public boolean getIsImportRequired() {
        return isImportRequired;
    }

    /**
     * Sets the value of the isImportRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsImportRequired(boolean value) {
        this.isImportRequired = value;
    }

}
