//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.12 at 03:50:50 PM IST 
//


package com.pvmsys.brix.graph.mappings.webServices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pamu package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HodsWebServices_QNAME = new QName("", "HodsWebServices");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pamu
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURLType() {
        return new URL();
    }

    /**
     * Create an instance of {@link Password }
     * 
     */
    public Password createPasswordType() {
        return new Password();
    }

    /**
     * Create an instance of {@link Username }
     * 
     */
    public Username createUsernameType() {
        return new Username();
    }

    /**
     * Create an instance of {@link HodsWebServices }
     * 
     */
    public HodsWebServices createHodsWebServicesType() {
        return new HodsWebServices();
    }

    /**
     * Create an instance of {@link HodsWebService }
     * 
     */
    public HodsWebService createHodsWebServiceType() {
        return new HodsWebService();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HodsWebServices }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HodsWebServices")
    public JAXBElement<HodsWebServices> createHodsWebServices(HodsWebServices value) {
        return new JAXBElement<HodsWebServices>(_HodsWebServices_QNAME, HodsWebServices.class, null, value);
    }

}
